// Prévia local com dados fictícios. Nunca copiar para o projeto Apps Script.
// Execute: node tests/preview.js e abra http://127.0.0.1:4173.
const fs=require('fs');
const http=require('http');
const path=require('path');
const root=path.resolve(__dirname,'..');
const requests=Array.from({length:32},(_,i)=>({id:i+2,versao:'fixture-'+i,unidade:['1º Juizado Especial Cível de Vitória','Juizado Especial de Vila Velha','2º Juizado Especial de Serra'][i%3],solicitante:['Pessoa de teste A','Pessoa de teste B','Pessoa de teste C'][i%3],email:'teste@example.invalid',data:'10/09/2026',dataIso:'2026-09-10T12:00:00Z',diasEspera:i%12,quantidade:'20',quantidadeNumerica:20,quantidadeValida:true,competencias:'Direito do consumidor',preferencia:'',status:i%4===0?'Pendente':i%4===1?'Concluído':'Em atendimento',juiz:i%4===0?'':'Juíza de teste A',dataDesignacao:'10/09/2026',observacoes:'Registro fictício para validar a interface.',prioridade:i%5===0?'Urgente':i%3===0?'Alta':'Normal',prazo:i%3===0?'2026-09-10':'2026-09-16',atrasada:i%3===0&&i%4!==1,atualizadoEm:'2026-09-11T12:00:00Z',detalhes:{processos:'0000000-00.2026.0.00.0000',orientacoes:'Exemplo fictício'}}));
const judge={id:80,nome:'Juíza de teste A',capacidade:'100',capacidadeNumerica:100,capacidadeValida:true,statusValido:true,cargaConfiavel:true,nomeDuplicado:false,requerRevisao:false,materias:'Direito do consumidor',observacoes:'Cadastro fictício',designadas:90,disponiveis:10,percentualOcupacao:90,lotado:false};
const data={usuario:{nome:'Gestor de demonstração',email:'teste@example.invalid',perfil:'ADMIN'},permissoes:{gerenciar:true,administrar:true},solicitacoes:requests,juizes:[judge,{...judge,id:81,nome:'Juiz de teste B',requerRevisao:true,capacidadeValida:false,capacidade:'A confirmar',capacidadeNumerica:0,disponiveis:null,percentualOcupacao:0}],fonte:null,statusPermitidos:['Pendente','Em atendimento','Concluído','Cancelado'],prioridadesPermitidas:['Normal','Alta','Urgente'],hoje:'2026-09-11',atualizadoEm:'2026-09-11T12:00:00Z',metricas:{total:32,pendentes:8,emAtendimento:16,concluidas:8,semJuiz:8,atrasadas:8,antigas:10,disponiveis:1,revisaoCapacidade:1}};
const mock=`<script>const fixture=${JSON.stringify(data)};const api={apiConfiguracaoPublica:()=>({nome:'Prévia fictícia'}),apiLogin:()=>({token:'fixture-token',usuario:fixture.usuario}),apiBootstrap:()=>fixture,apiHistoricoSolicitacao:()=>[],apiListarUsuarios:()=>[],apiLogout:()=>({ok:true}),apiAtualizarSolicitacao:()=>{throw new Error('Prévia: nenhuma alteração foi salva.');},apiDesignarJuiz:()=>{throw new Error('Prévia: nenhuma designação foi salva.');}};window.google={script:{run:{withSuccessHandler(ok){return{withFailureHandler(fail){return new Proxy({},{get:(_,name)=>(...args)=>setTimeout(()=>{try{ok(api[name](...args))}catch(e){fail(e)}},20)});}};}}}};window.print=()=>{document.body.classList.add('preview-print');};</script>`;
function html(){return fs.readFileSync(path.join(root,'src/index.html'),'utf8').replace("<?!= include_('Styles'); ?>",fs.readFileSync(path.join(root,'src/Styles.html'),'utf8')).replace("<?!= include_('startup'); ?>",fs.readFileSync(path.join(root,'src/startup.html'),'utf8')).replaceAll('<?= appName ?>','CONECTA JULES · Prévia com dados fictícios').replace("<?!= include_('App'); ?>",mock+fs.readFileSync(path.join(root,'src/App.html'),'utf8')).replace('<body>','<body><aside style="background:#fff4d6;padding:8px 16px;color:#805500">PRÉVIA LOCAL · Dados fictícios · Gravações desativadas</aside><style>.preview-print>*{display:none!important}.preview-print>#printReport{display:block!important;padding:24px}</style>');}
const server=http.createServer((req,res)=>{if(req.url==='/mobile'){res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end('<html><body style="margin:0;background:#cad3df"><iframe title="Prévia móvel com 390 pixels" src="/" style="border:0;width:390px;height:844px"></iframe></body></html>');return;}res.writeHead(200,{'Content-Type':'text/html; charset=utf-8'});res.end(html());});
if(process.argv[2]==='--export')fs.writeFileSync(process.argv[3],html());
else server.listen(4173,'0.0.0.0',()=>console.log('Prévia com dados fictícios em http://127.0.0.1:4173'));
