// Testes das funções reais da UI em DOM simulado; não substituem inspeção visual.
const fs=require('fs'),vm=require('vm'),assert=require('assert/strict');
const elements=new Map();
function element(id){if(!elements.has(id))elements.set(id,{value:'',hidden:true,checked:false,disabled:false,textContent:'',innerHTML:'',attrs:{},classList:{toggle(){}},setAttribute(k,v){this.attrs[k]=v;},addEventListener(){},focus(){},close(){this.open=false;},showModal(){this.open=true;},selectedOptions:[{textContent:id}]});return elements.get(id);}
const ctx=vm.createContext({console,Intl,Date,document:{getElementById:element,querySelectorAll:()=>[],querySelector:()=>null},window:{confirm:()=>true,print:()=>{ctx.printed=true;},scrollTo(){}},setInterval(){},setTimeout(){},clearTimeout(){}});
const code=fs.readFileSync('src/App.html','utf8').replace(/^<script>/,'').replace(/<\/script>\s*$/,'').replace(/boot\(\);\s*$/,'');
vm.runInContext(code,ctx);
const run=code=>vm.runInContext(code,ctx);
const records=Array.from({length:32},(_,i)=>({id:i+2,unidade:'Vitória',solicitante:'Pessoa '+i,status:'Pendente',prioridade:'Normal',juiz:'',quantidade:'20',quantidadeNumerica:20,quantidadeValida:true,prazo:'2026-09-16',diasEspera:2,detalhes:null,versao:'revision-'+i}));
ctx.fixture={solicitacoes:records,juizes:[],permissoes:{gerenciar:true,administrar:true},hoje:'2026-09-11',atualizadoEm:'2026-09-11T12:00:00Z',usuario:{perfil:'ADMIN'}};
run('state.data=fixture;state.token="token";');element('pageSize').value='10';element('sortFilter').value='newest';
let passed=0;function test(name,fn){fn();passed++;console.log('OK '+name);}
test('paginação limita o DOM e preserva página na releitura',()=>{run('renderRequests()');assert.equal((element('requests').innerHTML.match(/class="request-card/g)||[]).length,10);assert.equal(element('pageSummary').textContent,'Página 1 de 4');run('changeRequestPage(3);renderRequests(false)');assert.equal((element('requests').innerHTML.match(/class="request-card/g)||[]).length,2);assert.equal(element('nextPage').disabled,true);});
test('etiqueta separa quantidade ausente de valor inválido',()=>{ctx.r={...records[0],quantidadeInformada:false,quantidadeValida:false};const ausente=run('requestTags(r)');assert.match(ausente,/Quantidade não informada/);assert(!ausente.includes('Revisar quantidade'));ctx.r={...records[0],quantidadeInformada:true,quantidadeValida:false};assert.match(run('requestTags(r)'),/Revisar quantidade/);});
test('lista compacta mantém a página e as ações',()=>{run('setRequestView("table")');assert.equal(element('tableView').attrs['aria-pressed'],'true');assert.match(element('requests').innerHTML,/<table>/);assert.equal((element('requests').innerHTML.match(/onclick="openEdit/g)||[]).length,2);});
test('aba administrativa renderiza e abre o cadastro do juiz',()=>{ctx.judgeFixture=[{id:7,versao:'v7',nome:'Juiz <Teste>',email:'juiz@example.com',telefone:'27999990000',capacidadeValida:true,capacidadeNumerica:70,materias:'Cível',observacoes:'Meta',status:'Pendente',statusValido:true,ativo:true,nomeDuplicado:false}];run('state.judgeRecords=judgeFixture');element('adminJudgeSearch').value='';run('renderAdminJudges()');assert.match(element('adminJudgeCount').textContent,/1 de 1/);assert(!element('adminJudgesTable').innerHTML.includes('<Teste>'));run('openJudgeDialog(7)');assert.equal(element('judgeCapacityInput').value,70);assert.equal(element('judgeNameInput').value,'Juiz <Teste>');});
test('busca sem acento reinicia paginação e trata vazio',()=>{element('search').value='vitoria';run('renderRequests()');assert.equal(element('resultCount').textContent,'32 de 32 solicitação(ões)');assert.equal(element('pageSummary').textContent,'Página 1 de 4');element('search').value='inexistente';run('renderRequests()');assert.match(element('requests').innerHTML,/Nenhuma solicitação/);assert.equal(element('pagination').hidden,true);element('search').value='';});
test('prazo próximo respeita bordas e exclui encerradas',()=>{for(const [date,status,expected] of [['2026-09-10','Pendente',false],['2026-09-11','Pendente',true],['2026-09-18','Pendente',true],['2026-09-19','Pendente',false],['2026-09-16','Concluído',false],['','Pendente',false]]){ctx.item={prazo:date,status};assert.equal(run('isUpcoming(item)'),expected);}});
test('relatório inclui todas as páginas e escapa conteúdo',()=>{records[0].unidade='<img src=x onerror=alert(1)>';run('printRequests()');assert.equal(ctx.printed,true);assert.equal((element('printReport').innerHTML.match(/<tr>/g)||[]).length,33);assert(!element('printReport').innerHTML.includes('<img'));assert.match(element('printReport').innerHTML,/&lt;img/);element('search').value='Pessoa 31';run('printRequests()');assert.equal((element('printReport').innerHTML.match(/<tr>/g)||[]).length,2);element('search').value='';});
test('perfil consulta não recebe botões de gestão na lista',()=>{ctx.fixture.permissoes.gerenciar=false;run('renderRequests()');assert(!element('requests').innerHTML.includes('onclick="openEdit'));ctx.fixture.permissoes.gerenciar=true;});
test('reabertura apresenta excesso e mantém motivo separado',()=>{ctx.fixture.juizes=[{nome:'Juíza Teste',designadas:90,capacidadeNumerica:100,requerRevisao:false}];ctx.reopening={...records[0],juiz:'Juiza Teste',status:'Concluído'};run('state.currentRequest=reopening');element('editQuantity').value='20';element('editStatus').value='Em atendimento';run('updateReopenCapacity()');assert.equal(element('reopenFields').hidden,false);assert.match(element('reopenCapacity').textContent,/110 de 100/);element('editStatus').value='Cancelado';run('updateReopenCapacity()');assert.equal(element('reopenFields').hidden,true);});
(async()=>{
 let args;ctx.capture=(...values)=>{args=values;return {ok:true};};
 run('server=async(...args)=>capture(...args);loadData=async()=>{}');
 element('editStatus').value='Em atendimento';element('editId').value='2';element('editNotes').value='Reabertura justificada';element('editPriority').value='Alta';element('editQuantity').value='20';element('reopenReason').value='Exceção autorizada';element('reopenConfirm').checked=true;
 await element('saveButton').onclick();assert.equal(args[0],'apiAtualizarSolicitacao');assert.equal(args[7],records[0].versao);assert.equal(args[8],'Exceção autorizada');assert.equal(args[9],true);assert.equal(args[10],'20');passed++;console.log('OK gravação da UI transmite versão, confirmação e quantidade');
 await run('logout()');assert.equal(run('state.token'),'');assert.equal(run('state.data'),null);assert.equal(element('printReport').innerHTML,'');passed++;console.log('OK saída limpa sessão e relatório');
 console.log(`${passed} cenários de UI aprovados em DOM simulado.`);
})().catch(error=>{console.error(error);process.exitCode=1;});
